version: "3.7"

networks:
  prome-net:
    ipam:
      driver: default
      config:
      - subnet: "192.170.1.0/24"

volumes:
  prome-vol: {}

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    hostname: prometheus
    networks:
      prome-net:
        ipv4_address: 192.170.1.2
    restart: unless-stopped
    volumes:
    - prome-vol:/prometheus
    - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
  prome-nginx:
    image: nginx:alpine
    container_name: prome-nginx
    hostname: prome-nginx
    restart: unless-stopped
    depends_on:
    - prometheus
    network_mode: host
    volumes:
    - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    - ./certs:/etc/nginx/certs
