version: "3.8"

services:
    elastic:
        image: elasticsearch:5.6-alpine
        environment:
            - discovery.type=single-node
        networks:
            - internal
        ulimits:
            memlock:
                soft: -1
                hard: -1
    apiman-manager:
        image: apiman-manager:latest
        container_name: apiman-manager
        hostname: apiman-manager
        depends_on:
            - elastic
        volumes:
            - ./conf/apiman.properties:/opt/jboss/wildfly/standalone/configuration/apiman.properties
            - ./conf/standalone-apiman.xml:/opt/jboss/wildfly/standalone/configuration/standalone-apiman.xml
        ports:
            - 18080:8080
            - 18443:8443                
        networks:
            internal: {}
            matinet:
                ipv4_address: 11.0.0.7
                aliases:
                    - apiman-manager.matinet
networks:
    internal:
        name: internal
    matinet:
        external:
            name: matinet
