version: "3"

services:
    nexus:
        image: sonatype/nexus3:latest
        container_name: nexus
        hostname: nexus
        domainname: nexus.matinet
        networks:
            matinet:
                ipv4_address: 11.0.0.5
                aliases:
                    - nexus.matinet
        volumes:
            - nexus-data:/nexus-data
        ports: 
            - 8081:8081

networks:
    matinet:
        external:
            name: matinet

volumes:
    nexus-data:
        driver: local
