version: "3.7"

networks:
  nexus-net:
    ipam:
      driver: default
      config:
      - subnet: "192.170.1.0/24"

volumes:
  nexus-data: {}

services:
  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    hostname: nexus
    networks:
      nexus-net:
        ipv4_address: 192.170.1.2
    volumes:
      - nexus-data:/nexus-data
  nexus-nginx:
    image: fabiocicerchia/nginx-lua:1-alpine
    container_name: nexus-nginx
    hostname: nexus-nginx
    restart: unless-stopped
    depends_on:
    - nexus
    network_mode: host
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ./default.conf:/etc/nginx/conf.d/default.conf
    - ./certs:/etc/nginx/certs
