version: "3.7"

services:
    oracle:
        image: container-registry.oracle.com/database/enterprise:12.2.0.1-slim  
        container_name: oracle
        hostname: oracle
        privileged: true
        environment:
                - DB_PDB=fisco
                - DB_MEMORY=4GB
                - DB_DOMAIN=matinet
        volumes:
                - /data/oracle:/FISCO
        networks:
            matinet:
                ipv4_address: 11.0.0.2
                aliases:
                    - oracle.matinet

networks:
    matinet:
        external:
            name: matinet

