version: "3.7"

services:
    oracle:
        image: container-registry.oracle.com/database/enterprise:12.2.0.1
        container_name: oracle
        hostname: oracle
        privileged: true
        environment:
                - DB_PDB=fisco
                - DB_MEMORY=2GB
                - DB_DOMAIN=matinet
        ports:
                - 5500:5500
                - 1521:1521
        volumes:
                - /data/oracle:/vol1_4tb/Volumes/oracle/data/oracle
        networks:
            matinet:
                ipv4_address: 11.0.0.4
                aliases:
                    - oracle.matinet

networks:
    matinet:
        external:
            name: matinet

