version: '3.8'

networks:
  frontend:
    external:
      name: matinet
  storage:
    name: storage

volumes:
  datamongo: {}
  dataelasticsearch: {}

services:
  mongodb:
    image: mongo:latest
    container_name: gio_apim_mongodb
    restart: always
    volumes:
      - datamongo:/data/db
    networks:
      - storage
  elasticsearch:
    image: elasticsearch:7.6.2
    container_name: gio_apim_elasticsearch
    restart: always
    volumes:
      - dataelasticsearch:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile: 65536
    networks:
      - storage
  gateway:
    image: graviteeio/gateway:latest
    container_name: gio_apim_gateway
    restart: always
    ports:
      - "8082:8082"
    depends_on:
      - mongodb
      - elasticsearch
    environment:
      - gravitee_management_mongodb_uri=mongodb://mongodb:27017/gravitee?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
      - gravitee_ratelimit_mongodb_uri=mongodb://mongodb:27017/gravitee?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
      - gravitee_reporters_elasticsearch_endpoints_0=http://elasticsearch:9200
    networks:
      - storage
      - frontend
  management_api:
    image: graviteeio/management-api:latest
    container_name: gio_apim_management_api
    restart: always
    ports:
      - "8083:8083"
    links:
      - mongodb
      - elasticsearch
    depends_on:
      - mongodb
      - elasticsearch
    environment:
      - gravitee_management_mongodb_uri=mongodb://mongodb:27017/gravitee?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
      - gravitee_analytics_elasticsearch_endpoints_0=http://elasticsearch:9200
    networks:
      - storage
      - frontend
  management_ui:
    image: graviteeio/management-ui:latest
    container_name: gio_apim_management_ui
    restart: always
    ports:
      - "8084:80"
    depends_on:
      - management_api
    environment:
      - MGMT_API_URL=http:\/\/localhost:8083\/management\/
    networks:
      - frontend
