version: "3.7"

volumes:
  keycloak-vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${KEYCLOAK_VOL}

services:
  keycloak-postgres:
    image: postgres:12-alpine
    container_name: keycloak-postgres
    hostname: keycloak-postgres
    restart: unless-stopped
    volumes:
    - keycloak-vol:/var/lib/postgresql/data
    environment:
    - POSTGRES_USER=keycloak
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  keycloak:
    image: quay.io/keycloak/keycloak:11.0.2
    container_name: keycloak
    hostname: keycloak
    restart: unless-stopped
    ports:
      - 80:8080
    depends_on:
    - keycloak-postgres
    environment:
    - KEYCLOAK_USER=keycloak
    - KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD}
    - DB_VENDOR=postgres
    - DB_DATABASE=keycloak
    - DB_USER=keycloak
    - DB_ADDR=keycloak-postgres
    - DB_PASSWORD=${POSTGRES_PASSWORD}
    - KEYCLOAK_HTTPS_PORT=443
    - KEYCLOAK_ALWAYS_HTTPS=true
  keycloak-nginx:
    image: nginx:alpine
    container_name: keycloak-nginx
    hostname: keycloak-nginx
    restart: unless-stopped
    depends_on:
    - keycloak
    network_mode: host
    volumes:
    - $PWD/config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    - $PWD/certs:/etc/nginx/certs:ro

