version: '3.7'

volumes:
  nextcloud:
  db:

networks:
  nextnet:
    ipam:
      driver: default
      config:
        - subnet: "11.1.1.0/25"

services:
  #Database
  nextcloud-db:
    image: postgres:13-alpine
    restart: unless-stopped
    container_name: nextcloud-db
    hostname: nextcloud-db
    networks:
      nextnet:
        ipv4_address: 11.1.1.2
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=nextcloud
      - POSTGRES_DB=nextcloud
      - POSTGRES_PASSWORD=nextcloud
  
  #Application
  nextcloud:
    image: nextcloud:fpm-alpine
    container_name: nextcloud
    hostname: nextcloud
    volumes:
      - nextcloud:/var/www/html
    restart: unless-stopped
    environment:
      - POSTGRES_HOST=nextcloud-db
      - POSTGRES_USER=nextcloud
      - POSTGRES_DB=nextcloud
      - POSTGRES_PASSWORD=nextcloud
      - NEXTCLOUD_TRUSTED_DOMAINS=*
    depends_on:
      - nextcloud-db
    networks:
      nextnet:
        ipv4_address: 11.1.1.3
  
  #Web Proxy
  nextcloud-nginx:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - nextcloud:/var/www/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - nextcloud
    ports:
      - 9080:80
    networks:
      nextnet:
        ipv4_address: 11.1.1.4
  