version: "3.7"

services:
    vault:
        image: vault:latest  
        container_name: vault
        hostname: vault
        domainname: vault.matinet
        environment:
                - VAULT_DEV_ROOT_TOKEN_ID=root
                - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
                - VAULT_ADDR=http://0.0.0.0:8200
        cap_add:
                - IPC_LOCK
        volumes:
                - /data/oracle:/FISCO
        networks:
            matinet:
                ipv4_address: 11.0.0.6
                aliases:
                    - vault.matinet

networks:
    matinet:
        external:
            name: matinet

