version: '3.7'

networks:
  kong-net:
    name: kong-net
    ipam:
      driver: default
      config:
      - subnet: "192.170.2.0/24"

volumes:
  kong-postgres-vol:
    name: kong-postgres-vol
  konga-postgres-vol:
    name: konga-postgres-vol

services:
  kong-postgres:
    image: postgres:12-alpine
    container_name: kong-postgres
    hostname: kong-postgres
    restart: unless-stopped
    networks:
      kong-net:
        ipv4_address: 192.170.2.2
    volumes:
    - kong-postgres-vol:/var/lib/postgresql/data
    environment:
    - POSTGRES_DB=${KONG_POSTGRES_DB}
    - POSTGRES_USER=${KONG_POSTGRES_USER}
    - POSTGRES_PASSWORD=${KONG_POSTGRES_PASSWORD}
  kong:
    image: arquitectura/kong:latest
    container_name: kong
    hostname: kong
    restart: unless-stopped
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-postgres
      - KONG_PG_PORT=5432
      - KONG_PG_DATABASE=${KONG_POSTGRES_DB}
      - KONG_PG_USER=${KONG_POSTGRES_USER}
      - KONG_PG_PASSWORD=${KONG_POSTGRES_PASSWORD}
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001 reuseport backlog=16384, 0.0.0.0:8444 http2 ssl reuseport backlog=16384
      - KONG_PROXY_LISTEN=0.0.0.0:8000 reuseport backlog=16384, 0.0.0.0:8443 http2 ssl reuseport backlog=16384
    networks:
      kong-net:
        ipv4_address: 192.170.2.3
  konga-postgres:
    image: postgres:11-alpine
    container_name: konga-postgres
    hostname: konga-postgres
    networks:
      kong-net:
        ipv4_address: 192.170.2.4
    restart: unless-stopped
    volumes:
    - konga-postgres-vol:/var/lib/postgresql/data
    environment:
    - POSTGRES_DB=${KONGA_POSTGRES_DB}
    - POSTGRES_USER=${KONGA_POSTGRES_USER}
    - POSTGRES_PASSWORD=${KONGA_POSTGRES_PASSWORD}
  konga:
    image: pantsel/konga:latest
    container_name: konga
    hostname: konga
    environment:
    - NODE_ENV=production
    - TOKEN_SECRET=${TOKEN_SECRET}
    - DB_ADAPTER=postgres
    - DB_HOST=konga-postgres
    - DB_PORT=5432
    - DB_DATABASE=${KONGA_POSTGRES_DB}
    - DB_USER=${KONGA_POSTGRES_USER}
    - DB_PASSWORD=${KONGA_POSTGRES_PASSWORD}
    networks:
      kong-net:
        ipv4_address: 192.170.2.5
  kong-nginx:
    image: nginx:alpine
    container_name: kong-nginx
    hostname: kong-nginx
    restart: unless-stopped
    depends_on:
    - kong
    - konga
    network_mode: host
    volumes:
    - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    - ./stream.conf:/etc/nginx/conf.d/stream.conf:ro
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    - ./certs:/etc/nginx/certs:ro
