version: "3.7"

services:
    umbrella:
        image: nrel/api-umbrella
        container_name: umbrella
        hostname: umbrella.matinet
        domainname: matinet
        networks:
            matinet:
                ipv4_address: 11.0.0.4
                aliases:
                    - umbrella.matinet
networks:
    matinet:
        external:
            name: matinet

