version: "3"

services:
    portainer:
        image: portainer/portainer:latest
        container_name: portainer
        hostname: portainer
        ports:
                - 9000:9000
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

