version: "3.8"

services:
    kong:
        build: .
        image: kong:ubuntu-oidc
        container_name: kong
        hostname: kong
        ports:
                - 8000:8000
                - 18443:8443
                - 127.0.0.1:8001:8001
                - 127.0.0.1:8444:8444
                #- 9080:9080
        environment:
                - "KONG_DATABASE=postgres"
                - "KONG_PG_HOST=postgres"
                - "KONG_PG_PASSWORD=kong"
                - "KONG_PROXY_ACCESS_LOG=/dev/stdout"
                - "KONG_ADMIN_ACCESS_LOG=/dev/stdout"
                - "KONG_PROXY_ERROR_LOG=/dev/stderr"
                - "KONG_ADMIN_ERROR_LOG=/dev/stderr"
                - "KONG_ADMIN_LISTEN=0.0.0.0:8001 reuseport, 0.0.0.0:8444 http2 ssl reuseport"
                - "KONG_PROXY_LISTEN=0.0.0.0:8000 reuseport backlog=16384, 0.0.0.0:8443 http2 ssl reuseport backlog=16384"
                - "KONG_LOG_LEVEL=debug"
        networks:
            matinet:
                ipv4_address: 11.0.0.10
                aliases:
                    - kong.matinet
networks:
    matinet:
        external:
            name: matinet

