version: "3.7"

networks:
  keycloak-net:
    ipam:
      driver: default
      config:
      - subnet: "192.170.0.0/24"

volumes:
  keycloak-vol: {}

services:
  keycloak-postgres:
    image: postgres:12-alpine
    container_name: keycloak-postgres
    hostname: keycloak-postgres
    networks:
      keycloak-net:
        ipv4_address: 192.170.0.2
    restart: unless-stopped
    volumes:
    - keycloak-vol:/var/lib/postgresql/data
    environment:
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_DB=${POSTGRES_DB}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  keycloak:
    image: quay.io/keycloak/keycloak:10.0.2
    container_name: keycloak
    hostname: keycloak
    networks:
      keycloak-net:
        ipv4_address: 192.170.0.3
    restart: unless-stopped
    depends_on:
    - keycloak-postgres
    environment:
    - KEYCLOAK_USER=${KEYCLOAK_USER}
    - KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD}
    - DB_VENDOR=postgres
    - DB_ADDR=192.170.0.2
    - DB_DATABASE=${POSTGRES_DB}
    - DB_USER=${POSTGRES_USER}
    - DB_PASSWORD=${POSTGRES_PASSWORD}
    - KEYCLOAK_HOSTNAME=gaia.matinet
    - KEYCLOAK_HTTPS_PORT=443
    - KEYCLOAK_ALWAYS_HTTPS=true
  keycloak-nginx:
    image: nginx:alpine
    container_name: keycloak-nginx
    hostname: keycloak-nginx
    restart: unless-stopped
    depends_on:
    - keycloak
    network_mode: host
    volumes:
    - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    - ./certs:/etc/nginx/certs
