version: "3.8"

services:
    postgres:
        image: postgres  
        container_name: postgres
        hostname: postgres
        ports:
                - 5432:5432
        environment:
                - POSTGRES_PASSWORD=postgres
        volumes:
                - /data/postgres/data:/var/lib/postgresql/data
        networks:
            matinet:
                ipv4_address: 11.0.0.5
                aliases:
                    - postgres.matinet
networks:
    matinet:
        external:
            name: matinet

