version: "3.8"

services:
    elastic:
        image: elasticsearch:5.6-alpine
        container_name: elastic
        environment:
            - discovery.type=single-node
        networks:
            - internal
        ulimits:
            memlock:
                soft: -1
                hard: -1
    apiman-gateway1:
        image: apiman-gateway:latest
        container_name: apiman-gateway1
        hostname: apiman-gateway1
        depends_on:
            - elastic
        volumes:
            - ./conf/1/conf-es.json:/apiman-distro-vertx-1.5.5.Final/configs/conf-es.json
        ports:
            - 8081:8081
            - 8082:8082
            - 8444:8444  
        networks:
            internal: {}
            matinet:
                ipv4_address: 11.0.0.8
                aliases:
                    - apiman-gateway1.matinet
    #apiman-gateway2:
    #    image: apiman-gateway:latest
    #    container_name: apiman-gateway2
    #    hostname: apiman-gateway2
    #    depends_on:
    #        - elastic
    #    volumes:
    #        - ./conf/2/conf-es.json:/apiman-distro-vertx-1.5.5.Final/configs/conf-es.json
    #    ports:
    #        - 8082:8081
    #    networks:
    #        internal: {}
    #        matinet:
    #            ipv4_address: 11.0.0.9
    #            aliases:
    #                - apiman-gateway2.matinet
networks:
    internal:
        name: internal-gateway
    matinet:
        external:
            name: matinet
